# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Submit',
        ),
    ]
