# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20151217_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pdf_file_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='test',
            field=models.TextField(default=''),
        ),
    ]
