# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_testprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test',
        ),
    ]
