# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='accomplishment',
            field=models.BooleanField(default=False),
        ),
    ]
