# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0002_submit_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
