# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0003_submit_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit',
            old_name='executing',
            new_name='is_executing',
        ),
    ]
