# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20151228_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('shortname', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problems.Group'),
            preserve_default=False,
        ),
    ]
