# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_auto_20160206_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 6, 13, 56, 11, 311064, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
