# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_auto_20160207_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='problems',
            field=models.IntegerField(default=0),
        ),
    ]
