# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0017_auto_20160208_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='group',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
