# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_auto_20160208_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
