# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
