# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_privilege_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='sent',
            field=models.CharField(default='', max_length=255),
        ),
    ]
